### ISSUE TITLE
Errant newline inserted in sidebar

### ISSUE THREAD

**Issue by dreeves** [beeminder/blog#333]
```[tasklist]
### Desiderata
- [x] Diagnose what's going wrong with the markdown renderer
- [x] Fix the bug
- [x] Danny confirms fix by undoing at least one of the workarounds and seeing it not break
```

## Replicata 

1. Go to http://blog.bmndr.co/postel
2. See the first sentence of the "Prof. Yorgey’s Anecdote" sidebar

## Expectata

An unbroken sentence: "You may remember Brent Yorgey from such Beeminder blog posts as..."

## Resultata

![image](https://github.com/beeminder/blog/assets/9928/177a516b-2074-4485-8b31-0f9c8949d6fa)

It's sticking in an extra `<p>` tag for reasons I can't fathom.

## Cognata

* #328

_**Verbata**: newlines, markdown rendering, extra p tags, extra newlines, formatting, mixing html and markdown,_

**Comment by dreeves** [comment]
PS: I've worked around this in the meantime by replacing the space after "Brent Yorgey" with "&nbsp;". But there may be other instances so we still need to debug it.

**Comment by narthur** [comment]
@dreeves That url is to the blog homepage. What's the url to the specific post in question?

**Comment by dreeves** [comment]
Fixed the link in the replicata. Sorry about that. In the meantime users have found other instances of this bug in other posts.

**Comment by dreeves** [comment]
For example, see the sidebars in https://blog.beeminder.com/gatewaydrug -- seems to happen after every link.

**Comment by dreeves** [comment]
Update: not just in sidebars!

I came across the following in https://blog.beeminder.com/control/ :

![image](https://github.com/beeminder/blog/assets/9928/55b50341-2324-49d7-83f6-be4744a8226f)

It's rising to the level of embarrassment that i think it's worth calling this a bit urgent. I'm going to go in and work around it for the above post before I link someone to it but clearly there are a lot of instances of this bug out there.

**Comment by narthur** [comment]
This was caused by a previous attempt I made to fix a discrepancy between the old markdown renderer and the new one, where I made the build go through and automatically add new lines after any html elements that had at least one newline after it.

I think I'd prefer to just not do that anymore, and say we fix any issues that result manually. That way we're doing better at respecting anti-magic, and the builds are likely to be faster.

I do think we should do some checking around to make sure that change wouldn't break too many things. Here's a preview link with that functionality turned off:

https://beeblog-pr-351.onrender.com/

@dreeves Are you good with this direction?

**Comment by narthur** [comment]
For a bit more context, here's the test suite for that functionality:

```
import addBlankLines from "./addBlankLines";
import { describe, it, expect } from "vitest";

describe("addBlankLines", () => {
  it("adds blank lines", () => {
    const markdown = "<h1>heading</h1>\nparagraph";

    const result = addBlankLines(markdown);

    expect(result).toEqual("<h1>heading</h1>\n\nparagraph");
  });

  it("adds blank lines after any html element", () => {
    const markdown = "<div>hello</div>\nparagraph";

    const result = addBlankLines(markdown);

    expect(result).toEqual("<div>hello</div>\n\nparagraph");
  });

  it("does not add blank lines after inline elements", () => {
    const markdown = "<div><span>hello</span></div>\nparagraph";

    const result = addBlankLines(markdown);

    expect(result).toEqual("<div><span>hello</span></div>\n\nparagraph");
  });
});
```

**Comment by dreeves** [comment]
I spotted a bizarre regression in that PR build:

![image](https://github.com/beeminder/blog/assets/9928/dc8c0b60-216d-45af-a68a-b851b25d33f0)

(note the different font)

**Comment by narthur** [comment]
@dreeves Yup, entirely expected. This is the relevant markdown for that page:

```
<h4 class="pullquote">"describe a task, start a timer, and get down to work"</h4>
What does that have to do with deep work?
Maybe you like trydeepwork.com but you keep forgetting to start sessions?
Beeminder does not let you forget.
```

Since Marked expects newlines around block-level raw HTML, it ignores that paragraph and fails to surround it with `<p>` tags. So it doesn't end up formatted since our typographic styles target `<p>` tags.

Adding a newline between that heading and the following paragraph would fix it.

**Comment by dreeves** [comment]
Oh man, this is code-smelly, right, if we're mole-whacking like that? Can we step back / rethink? What does an off-the-shelf markdown renderer do and why/how have we deviated from that?

**Comment by narthur** [comment]
@dreeves So the underlying issue is that Mark Gruber released the Markdown spec in 2004 and then never changed it. That means that if anyone wanted new features not in the original spec, they had to extend the original spec however they saw fit, resulting in a universe of Markdown flavors that are incompatible with each other to varying degrees, and may even take liberties with the original Markdown specification.

As far as where we're at with the new blog:

- We're using [Marked](https://www.npmjs.com/package/marked) as our off-the-shelf parser.
- I used [this Marked plugin](https://www.npmjs.com/package/marked-smartypants) to add Smartypants.
- I use [gray-matter](https://www.npmjs.com/package/gray-matter) to extract and parse the frontmatter.

Additionally, I have custom code for the following features:

- [Adding blank lines around paragraphs](https://github.com/beeminder/blog/blob/02a3db76b6fcae858c051fea290292f5db20edf4/src/lib/addBlankLines.ts) (resulting in this issue)
- [Magic tags](https://github.com/beeminder/blog/blob/db0815757033498c338ea171b30582dce8e46cd1/src/lib/trimContent.ts)
- [Fancy footnotes](https://github.com/beeminder/blog/blob/4008eb1da1b4a44af20cfd0ae7eee00b330477c3/src/lib/linkFootnotes.ts)
- [Fancy ref numbering](https://github.com/beeminder/blog/blob/c1364e53f9c0936ae63ee26b4742dc19795d57bc/src/lib/expandRefs.ts)
- [Extracting first image](https://github.com/beeminder/blog/blob/409a4287eeed2d4987a8ee18141383bb08426c8b/src/lib/extractImage.ts)
- [Extracting the magic title](https://github.com/beeminder/blog/blob/9dab028e96eeefd0c5c0bdf08d1f2aa46b7d2952/src/lib/parseTitle.ts)
- [Applying `{#foo}` IDs to resulting HTML elements](https://github.com/beeminder/blog/blob/409a4287eeed2d4987a8ee18141383bb08426c8b/src/lib/applyIdsToElements.ts)

---

Aside: According to my reading of [Gruber's Markdown documentation](https://daringfireball.net/projects/markdown/syntax#p), Marked is handling paragraphs correctly as opposed to what was previously happening with the WordPress blog:

> A paragraph is simply one or more consecutive lines of text, separated by one or more blank lines. (A blank line is any line that looks like a blank line — a line containing nothing but spaces or tabs is considered blank.) Normal paragraphs should not be indented with spaces or tabs.
