### ISSUE TITLE
OpenGraph fields missing for blog home page

### ISSUE THREAD

**Issue by dreeves** [beeminder/blog#341]
```[tasklist]
### Desiderata
- [x] Deploy fix
- [x] Tweet the UVI on 2023-08-28
```

## Replicata 

1. Share a link to the blog home page -- http://blog.bmndr.co -- not a specific post to Discord or social media or whatever.

## Expectata

To see an image and blurb.

## Resultata

Just the word "home" in Discord, and the forum complains like so:

![image](https://github.com/beeminder/blog/assets/9928/bf66c945-f317-42aa-ac3b-6a8b84bcf78c)

<img width="219" alt="image" src="https://github.com/beeminder/blog/assets/9928/b5bb6dad-a38d-4dc1-ac1a-4b7064d661d3">

## Cognata

* #353 (PR FOR THIS)
* http://beeminder.com/changelog#4225 (THIS UVI)

_**Verbata**: SEO, mendoza,_

**Comment by narthur** [comment]
@dreeves Looks like this is an issue with the home page specifically, since we're already including these tags for posts:

<img width="600" alt="Screenshot 2023-08-27 at 12 40 48 PM" src="https://github.com/beeminder/blog/assets/4655422/1bcaa2f8-cb7d-4d15-9c63-8804ac2cfb00">

I guess I could resolve this by updating the main layout template to require these properties to be set for every page on the site.

**Comment by narthur** [comment]
Fixed: 

<img width="632" alt="Screenshot 2023-08-27 at 2 46 13 PM" src="https://github.com/beeminder/blog/assets/4655422/1b0128d6-162b-43af-8081-dbc123b7dd27">

**Comment by dreeves** [comment]
Where does that "Home" come from? Can it be "Beeminder blog" or "Beeminder blog homepage" instead?

**Comment by narthur** [comment]
Sure thing:

<img width="601" alt="Screenshot 2023-09-11 at 11 05 38 AM" src="https://github.com/beeminder/blog/assets/4655422/e4f8c9c6-78a7-4e11-8396-d3ef26232175">
