### ISSUE TITLE
Unintended text wrapping in post lists

### ISSUE THREAD

**Issue by narthur** [beeminder/blog#374]
```[tasklist]
### Desiderata
- [x] Narthur puts it how he intended
- [x] Bee opines
```

![Screenshot_20230913_062327](https://github.com/beeminder/blog/assets/4655422/f352ec4b-7e8a-4354-9d04-74ebd9282db7)

Text wrapping around the images like this is a regression.

**Comment by narthur** [comment]
Fix deployed

**Comment by dreeves** [comment]
After: 
![image](https://github.com/beeminder/blog/assets/9928/2e01ed94-468c-4184-836f-22f68d601b02)

Are we sure we disliked the wrapping? Maybe it's nice? I don't know, I'm bad at aesthetics, but maybe Bee could weigh in unless you're sure it's better this way.

**Comment by narthur** [comment]
@dreeves Hmm, that definitely is how I intended it to work at small screen widths. I guess I should reconsider that choice?

**Comment by narthur** [comment]
@dreeves @bsoule Closing this now, since the original bug is fixed. If there's a desire to reconsider the design intention here let's create a new issue.

**Comment by dreeves** [comment]
Set me straight if I'm creating bad workflows but since this one has the screenshots and stuff I'd rather leave it open till Bee chimes in. She may say it's fine and we can just close this. But with this closed we have nothing to remind us to get a new gissue created if we do want to change something about this.

**Comment by bsoule** [comment]
after mobile / small scale is good:

<img width="409" alt="Screen Shot 2024-03-06 at 15 26 14" src="https://github.com/beeminder/blog/assets/46881/07d6d1fe-167c-4614-8709-4c41b6d0cd75">

after for the desktop / large scale is fine:

<img width="868" alt="Screen Shot 2024-03-06 at 15 25 47" src="https://github.com/beeminder/blog/assets/46881/29951fd9-7518-4ae4-9c25-e5474761816e">

I maybe have a slight preference for the "before" version above, with the text wrapping around the image, except maybe  because of the variablility of the length of the excerpts, it might be better the way it currently is?

like if some excerpts are long and wrap below the image, and then others are shorter and don't wrap, maybe that would look worse than the status quo? i have a slight, though not strong, prediction that it'd be ugly for some to have text below the image and others without (jsut cuz the excerpt is too short).
