### ISSUE TITLE
Unreadable, overlapping text and images

### ISSUE THREAD

**Issue by dreeves** [beeminder/blog#393]
```[tasklist]
### Desiderata
- [x] Deploy fix
- [x] Postmortem and link to PR or commit
```

## Replicata 

1. Go to https://blog.beeminder.com/apps on desktop

## Expectata

To be able to read the post.

## Resultata

![image](https://github.com/beeminder/blog/assets/9928/7da3e641-0523-42e2-9b4c-dfab3434a6ef)

## Cognata

* #392 

_**Verbata**: mendoza, css,_

**Comment by narthur** [comment]
This is fixed

**Comment by dreeves** [comment]
Do you have a link to the commit or PR? Hearing a postmortem might be nice, in case it suggests a broader issue worth addressing.

**Comment by narthur** [comment]
@dreeves The fix was surrounding the two images with `<div style="overflow: hidden;">...</div>` in the markdown. No changes were made to the blog's code to handle this case. I think this is the right call because the issue was introduced by `style` attributes applied inside the raw markdown, and it doesn't seem reasonable to me to expect the blog to use defensive styling to try to shield against markdown's ability to include arbitrary CSS in posts.
